### ISSUE TITLE
Use the flash

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#25] opened 2015-10-19 11:38 UTC
We should experiment also if using the flash helps get the right quality. Perhaps you could build in a way for us to turn it on/off (for development first)

**Comment by ldporsius** [comment] 2015-10-26 17:16
I wrote some to set the camera parameters to use flash mode. I think it works fine. Just tested a couple of times. I set the 'brightness' icon to function as a switch. Turn flash on/off.

**Comment by ldporsius** [comment] 2015-10-29 13:44
I observed that if the torch is lit, the brightness gets lower. This is contrary to what one would expect maybe. I think it is because of the auto-exposure-compensation of the Android camera.

**Comment by ldporsius** [comment] 2015-11-02 07:11
I experimented with the setting of exposure compensation. It does not change the fact that when the flash/torch is on, the brightness get's lower or in the best case: stays the same.
Also, because you are forced to hold the camera at a distance below the card, the torch is not lighting the whole card and shadows are cast.
We could let go of the torch, or we could move the window that shows the card to the center?

**Comment by mtwestra** [comment] 2015-11-02 07:41
Let’s get rid of the torch for now

**Comment by ldporsius** [comment] 2015-11-02 07:57
I thought maybe it can help if a shadow is cast from another source, to compensate for that, but the effect is not very drastic.

**Comment by mtwestra** [comment] 2015-11-02 08:05
Ah yes, it would certainly help for that. perhaps that when we can use the API v2, which allows direct control over exposure, this could be useful again. 

I guess the api v1 doesn’t allow that, right?
mark

**Comment by ldporsius** [comment] 2015-11-02 08:32
I think that allowing the user to adjust exposure may be to complex for this app. It should be done programmatically then, but it is hard to tell the camera in which direction it should adjust it's exposure. 
I'm not even sure it has any effect what so ever, it's hard to tell. There are issues, especially with Samsung devices: http://stackoverflow.com/questions/14373262/setexposurecompensation-does-not-work-in-samsung-galaxy-s3. And it so happens that I have a Samsung Galaxy Ace III.

The camera preview sees a lot of the surroundings besides the card, whereas the exposure (brightness) quality check is based on the difference between min and max grey values of the finder patterns. Wouldn't that mean, that if e.g. I put the card on a shimmering surface like a white shiny table in the sun, the camera is going to compensate the exposure by setting the value to a negative number. (zero means: do not adjust, -1 means smaller aperture (?), etc.)
So even if the card is evenly lit and not to bright, this situation might effect the exposure, or not?

I tried if I could notice any difference between a) card on shiny white surface and b) card on black piece of cloth. If a) the whole card get's darker. If b) the card get's a lot brighter. This is the same with torch on or off. But the brightness indicator keeps the same value: around 70% this time around. We measure brightness as the diff between black and white in the finder patterns, so it is relative per sé.

**Comment by mtwestra** [comment] 2015-11-02 08:54
I’m not sure I understand - can you use the API V1 to change the exposure? If so, we could still posibly use it:

1) set exposure
2) find finder pattners
3) based on exposure measure, adjust exposure
4) repeat until ok

m

**Comment by mtwestra** [comment] 2015-11-02 08:57
From this, it seems that exposurecompensation is supported, up from level 8. Something we could try? Possibly with my phone?

m

**Comment by ldporsius** [comment] 2015-11-02 08:58
I am thinking along the same line Mark, but it is to early to say, not until I get it working.

**Comment by mtwestra** [comment] 2015-11-02 09:09
The idea would be that we can adjust the exposure dynamically ourselves, using the measured spread of luminosity and min/max values of the finder patterns.

In the same way, android measures the focus: adjust focus, measure contrast, repeat.
m

**Comment by mtwestra** [comment] 2015-11-02 09:13
From this, I see we can also set the white balance: http://developer.android.com/reference/android/hardware/Camera.Parameters.html#getWhiteBalance() http://developer.android.com/reference/android/hardware/Camera.Parameters.html#getWhiteBalance()

It might probably be an idea to fix the setting to WHITE_BALANCE_DAYLIGHT

mark

**Comment by ldporsius** [comment] 2015-11-02 10:03
OK, it seems you can adjust exposure at runtime. What do you mean by: 
'using the measured spread of luminosity and min/max values of the finder patterns.'
We now look at the min/max values. What is the 'measured spread'?

**Comment by ldporsius** [comment] 2015-11-02 10:13
![device-2015-11-02-111159](https://cloud.githubusercontent.com/assets/9623423/10879155/96fb5d8c-8152-11e5-9b24-b53bd2712ebc.png)

The problem is, that when we take the diff between min and max from the grayscale finder pattern mats, in this example you see that Brightness is around 60%, while in my view this image is clearly over-exposed.

**Comment by mtwestra** [comment] 2015-11-02 10:15
You could observe the minimum and maximum luminosity, and then adapt:

1) set the exposure to the camera’s best guess, and lock it
2) if the minimum lum = 0, meaning black is completely black, increase the exposure
3) if the maximum is 255, decrease the exposure
4) repeat 

m

**Comment by mtwestra** [comment] 2015-11-02 10:16
Yes, good point. so we need to take into account the minimum and maximum values.

**Comment by ldporsius** [comment] 2015-11-02 10:18
Secondly: if the image is over-exposed like this, it becomes impossible to find the finder patterns. That means that the percentage of luminosity is zero. That means that exposure-compensation will be triggered to even larger values.

**Comment by mtwestra** [comment] 2015-11-02 10:21
You can solve that by looking at the min/max instead:

1) if the max = 255, then decrease the exposure
2) if the min = 0, then increase the exposure
3) if both max < 255 and min > 0, we are probably good. this case might be more difficult to check, but we can start with the two above

**Comment by ldporsius** [comment] 2015-11-02 10:31
If no finder patterns are found, there are no min/max values.
Either: do not reset the value with every loop
Or: if no finder patterns, change exposure in a way that if high << and if low >>

**Comment by mtwestra** [comment] 2015-11-02 10:35
So we could do:

1) use automatic exposure 
2) try to find finder patterns
3) when finder patterns found, lock exposure
4) look at min / max and adjust exposure to see if we can improve.

**Comment by ldporsius** [comment] 2015-11-02 11:03
Exposure is always done, automatically. You can adjust the value of the exposure. If you set it to zero, it does not compensate for the auto-value, but that does not mean that there isn't a value for the exposure, it is just not overruled. If I am not mistaken that is.
Locking means that 'the camera auto-exposure routine will immediately pause ' (http://developer.android.com/reference/android/hardware/Camera.Parameters.html#setAutoExposureLock%28boolean%29)

I'll try and see what it yields.

**Comment by ldporsius** [comment] 2015-11-02 11:13
From the logcat:

 _**lumMinMax   29  255
 *__lumMinMax   17  255
 *__lumMinMax   30  251
 *__lumMinMax   15  253
 *__Exposure compensation brightness    93.3333333333  
 *_*Exposure compensation   12  

The quality was OK, not over nor under exposed. So I guess that values of 255 do not mean that it is to bright.

My device has 12 as MaximumExposureCompensation.

**Comment by ldporsius** [comment] 2015-11-02 11:21
I think we could try this:

If max == 255 and min >> : we are triggering over exposure
If min == 0 and max << : we are triggering under exposure

Keep track of previous values for min and max so we can compare them.
If an optimum is reached, and one of the above is true, do not adjust exposure.

**Comment by mtwestra** [comment] 2015-11-02 11:34
255 means that values are being cut off, which means losing information, so ideally there should not be any 255 in an image

**Comment by mtwestra** [comment] 2015-11-02 11:35
yes, exactly

**Comment by ldporsius** [comment] 2015-11-03 15:53
I should explain about the 'reset camera' part in the last commit, as it is really not something I can defend. It is based on trial and error as follows: We use the brightness icon to switch the flash/torch on and off, but what that really did, was call the onSurfaceChanged method of the BaseCameraView class (that implements SurfaceHolder.Callback). When I tested today I pressed that icon a lot and that triggered the camera to alter its exposure. Now I have no idea how Android sets its auto-exposure value and despite extensive use of the well known search engine, I cannot find anything that explains it. The effect however is, that when I go from inside to outdoors, from dusk to sun, the exposure finds it necessary to adjust itself. From there, the compensation can do the job of fine-tuning.

**Comment by ldporsius** [comment] 2015-11-04 16:07
This issue is about the use of flash/torch, but now it has become about exposure compensation.

**Comment by ldporsius** [comment] 2015-11-04 16:25
We based the luminosity check upon the difference between min and max values of the (gray-scale) image of the finder pattern with the lowest value. The criterium is: the difference in percentage must be above 60%. That would mean that if black = 0, white must be 153. That is not very bright. 
Regarding the calibration, is an image as dark as this a good enough basis? Or should we not look at the difference but at the absolute value of the 'white' as indicator of the brightness?
The latest commit does the latter.

**Comment by ldporsius** [comment] 2015-12-09 17:07
The flash can be turned of and on by an onClickEvent. We do not draw any attention to it. If the user takes care to do a test under reasonable light conditions, it should not be necessary to use flash.

**Comment by ldporsius** [comment] 2015-12-12 09:32
Closing.

**Closed as completed by ldporsius** 2015-12-12 09:32 UTC
Labels: Strip test
