### ISSUE TITLE
No result with HACH pH test

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#135] opened 2017-09-21 09:50 UTC
I was testing a simple Flow form with pH HACH test type question. I used the 1.0.0 Beta 8.5 version of the Caddisfly app. After multiple trials I always received the No result screen after running the test. All the preparations steps where the light conditions are checked went smoothly and also the test itself. 

I did not try any other Caddisfly test types to confirm if it only happens for this one test type or for all on my device. 

![screenshot_2017-09-21-11-32-06](https://user-images.githubusercontent.com/12456965/30689995-02e63154-9ec3-11e7-8838-12e171b658d5.png)

**Comment by arthurakvo** [comment] 2017-09-21 10:26
Hi Jana,

I quickly performed two Hach pH tests here with two different phones using a new version of the app and did experience the same issue. The new app will be released in a few days and then we will test again to make sure the issue is solved. Thanks!

**Comment by janagombitova** [comment] 2017-09-21 12:24
@nhternup I tried the APK you shared with me (1.0.0 Beta 9 Test 2) and once I got the result, but then right after I did not. I tested out a few times and out of the 7 trials I had one successful one.

**Comment by arthurakvo** [comment] 2017-09-22 03:51
Apologies: I meant to say I did not experience this issue on two different phones.

**Closed as completed** 2018-01-24 08:48 UTC
